name: Deploy SOLUTCLOUD Portal

on:
  push:
    branches:
      - main  # Vérifie bien si ta branche s'appelle main ou master

jobs:
  web-deploy:
    name: 🚀 Deploy to login.solutcloud.com
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: 💿 Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql, ftp

      - name: 📦 Install Dependencies (Composer)
        env:
          COMPOSER_AUTH: '{"github-oauth": {"github.com": "${{ secrets.GITHUB_TOKEN }}"}}'
        run: composer install --no-dev --optimize-autoloader --ignore-platform-req=php+

      - name: 🏗️ Build Assets (NPM)
        run: |
          npm install
          npm run build

      - name: 🚀 Sync Files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          # ON ENLÈVE /htdocs/ CAR LA CONNEXION NOUS Y PLACE DÉJÀ
          # HOPE
          server-dir: login.solutcloud.com/ 
          exclude: |
            **/.git*
            **/node_modules/**
            **/tests/**
            .env
            